# Generated by Django 5.0.2 on 2024-06-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('display_content', models.TextField()),
                ('main_content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
