# Generated by Django 5.0.6 on 2024-05-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=2)),
                ('joiningDate', models.DateField()),
                ('passingDate', models.DateField()),
                ('achievments', models.CharField(max_length=500)),
                ('present', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('employment', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=200)),
            ],
        ),
    ]
